spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 566a1df05af5024d49f1
            client-secret: dae1fefad93b41a4dd1f45886e6b86e1e36d867d
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sessionsdata
    username: destiny
    password: "@Destiny98"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: MySQL
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG